site_name: Changelog

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

copyright: Copyright &copy; 2021 - 2022 BochumRP

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.io/BochumRP
